name: plant_clinic
description: A Flutter app for detecting plant diseases using TFLite
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tflite: ^1.0.1
  image_picker: ^0.8.5+3
  permission_handler: ^11.3.0
  image: ^3.2.0
  cupertino_icons: ^1.0.6


flutter:
  uses-material-design: true
  assets:
    - assets/models/model.tflite
    - assets/models/labels.txt
